### ISSUE TITLE
PCBA files for 52?

### ISSUE THREAD

**Issue by ramnathk** [mmccoyd/hillside#14]
Hi there, could you publish the PCBA files for the 52 key version of the keyboard please?

**Comment by mmccoyd** [comment]
Done I believe. They are in the zip in the release.

It is a prerelease, in that I have not physically tested it, and likely will not get to. But it displays properly in JLC order system. It should work fine. Please let me know if it works for you or you have any issues with it. Then I can remove the prerelease marking.

**Comment by mmccoyd** [comment]
It was a issue fix for JLC no longer liking the Gerber files. But PCBA got added to it.

**Comment by ramnathk** [comment]
Awesome and than you mate
