### ISSUE TITLE
keyboard-layout-editor.com file

### ISSUE THREAD

**Issue by mankoff** [mmccoyd/hillside#15]
Does anyone have a layout file for keyboard-layout-editor for a Hillside keyboard?

**Comment by mmccoyd** [comment]
The Readmes in the 52 and 46 folders have links to layout files.

**Comment by mankoff** [comment]
Actually re-opening. If I paste https://raw.githubusercontent.com/wiki/mmccoyd/hillside/hill_46/keyboard-layout-editor.json or https://raw.githubusercontent.com/wiki/mmccoyd/hillside/hill_52/keyboard-layout-editor.json into the `</> Raw Data` tab here http://www.keyboard-layout-editor.com/#/ I get an empty square.

**Comment by mmccoyd** [comment]
You need to save locally, then use the Upload JSON a the bottom of that tab.
