### ISSUE TITLE
Add more parts to PCBA

### ISSUE THREAD

**Issue by auipga** [mmccoyd/hillside#16]
Hi,
first of all, thank you for this sophisticated piece of awesomeness! Even the LEDs are hidden _behind_ a key. You're a genius!

I've read the Wiki and if I'm right I need to solder some parts myself after PCBA service:
- SK6812MINI-E https://jlcpcb.com/partdetail/OpscoOptoelectronics-SK6812MINIE/C5149201
- Rotary Encoders https://jlcpcb.com/partdetail/Alpsalpine-EC12E1220301/C209763
- Machine pin female sockets like this https://www.mouser.de/ProductDetail/Mill-Max/315-43-112-41-003000?qs=s8Nb1z4Wn%2FRfWrVqQ0TOuQ%3D%3D
- Mill-Max Hot Swap Sockets https://jlcpcb.com/partdetail/millmax-7305_0_15_15_47_27_100/C5189908

Is it possible to add those to the PCBA too?
Regards

**Comment by mmccoyd** [comment]
Hi. Thanks.

A short reply for the moment.

The LEDs could be possible, but they are only supported for the Standard PCBA process, not the Economical one. Which raised the setup price from a modest $8 per side to $25 per side. They are one of the more challenging bits to solder, so it might be good idea, if I can prevent it causing confusion for the normal Economical PCBA process. Thanks.

A risk of adding the encoders to the PCBA is that people who did not really want encoders might still just send the files as is without checking them and deselecting the encoders. I'd say encoders are as easy to solder as switches, and more of a pain to desolder.

A different PCBA manufacturer provides more capabilities, but at higher price. I've not yet looked at using them. I expect they could do the MCU sockets, but I'm not sure about the switch Mil-Max.

**Comment by auipga** [comment]
Hi Michael. Thank you for your detailed reply.

The LEDs would be the most interesting. What I didn't understand is whether the more expensive standard PCBA Type is evitable or not.

The rest would be ok to solder myself.

**Comment by auipga** [comment]
Now that I decided to pay that price for the standard PCBA type, I'd like to add whatever is possible.
Could you help me achieve this / guide me through the process?
All I can get to is this:
![photo_2022-11-30_10-35-50](https://user-images.githubusercontent.com/876689/204760344-9adc149f-d28c-442a-acd2-890d1be34aff.jpg)

What is the correct way to add and position new parts to existing footprints?

**Comment by mmccoyd** [comment]
Hi. I'm adding that to the release zip, thought it might be a day or two. 

Either of the power switches should be fine. Moving to oval holes expanded the switch choices, but I've not fully updated the docs yet.

**Comment by auipga** [comment]
Hi, just wanted to ask whether I can do something for you to get it done?
