### ISSUE TITLE
How to mount encoder

### ISSUE THREAD

**Issue by tim-hilt** [mmccoyd/hillside#20]
I have ordered all required parts to build my Hillside. The only thing I don’t really know with is how to solder the encoders. One of the holes in the PCB doesn’t seem to be wide enough.

Here’s a photo of what I mean:

![2A7735EA-D651-40A0-AF93-C61FA4F6DDB1](https://user-images.githubusercontent.com/16037579/224731475-d0d9adc4-8821-4e2d-9d02-3422e0d3796e.jpeg)

How am I supposed to deal with this? Do I just cut off the second wide leg?

**Comment by mmccoyd** [comment]
Tim, Yes, just cut off the circled wide leg. I'd update the docs if it's not there. A wide leg hole and LED would not go well together. I hope you like the board.

**Comment by tim-hilt** [comment]
Thanks for the response! :) I’m very excited to see how the Hillside works for me! Thank you!
