### ISSUE TITLE
JLCPCB's PCA preview shows Hillside 46 components misplaced

### ISSUE THREAD

**Issue by jfhector** [mmccoyd/hillside#21]
Hello!

Thanks a lot for this wonderful looking keyboard, and the very helpful detailed instructions!

I'm following the instructions on the [Ordering Hillside 52 or 46 page](https://github.com/mmccoyd/hillside/wiki/Ordering%20Hillside%2052%20or%2046), in order to order a Hillside 46 from JLCPCB.

I'm following the steps detailed in the doc step by step, but after uploading the BOM and top_boards.csv, JLCPCB's preview shows the components positioned completely off the PCB:

![capture-2023-04-12T12_56_43 580Z](https://user-images.githubusercontent.com/30028540/231464207-10646ef5-5f26-40f5-8424-f8da72614d64.png)

This seems to be the only preview JLCPCB shows before placing the order. I've redone the steps three times and I don't think I've missed anything. Is it the case that I've missed anything, or is there an issue with JLCPCB or with the instructions?

### Steps to reproduce

1. Download hillside46-gerber-and-pcba_0.1.0 from [Releases](https://github.com/mmccoyd/hillside/releases) [hill46_v0.1.0](https://github.com/mmccoyd/hillside/releases/tag/hill46_v0.1.0).

2. On JLCPCB, follow the instructions from [How to Order Five PCBA Keyboards](https://github.com/mmccoyd/hillside/wiki/Ordering%20Hillside%2052%20or%2046#how-to-order-five-pcba-keyboards)

    Side note: The instructions say "Dimensions: 100 x 143 mm". But after uploading the Gerber file, dimensions are pre-populated and are slightly different: 142.49 width, 99.87 height.

3. At the 'Save to Cart' step, which reads ...
    > The preview should show components placed and rotated over spots on the board that look meant for them, in terms of silkscreen lines around them and traces leading to them. The engineers will ensure the final placement, and you will confirm at DFM Analysis later.
    
    ... the components on the preview are placed away from the PCB board.

**Comment by jfhector** [comment]
Looking at other people's experience, it may be an issue with JLCPCB's viewer, and the assembly may come back fine:
https://www.eevblog.com/forum/manufacture/jlcpcb-smt-weird-issue-with-part-placements/

**Comment by jfhector** [comment]
JLCPCB have posted a blog post which seems to be about that issue, with reassurance that it's fine:
https://github.com/JLCPCB/JLCPCB-SMT-Assembly-Components-orientation-fix

I'm closing the issue as I don't expect this is a problem with the instructions in this repo.

**Comment by Max-Stevens** [comment]
On the note of the part misalignment, the placement for U2 isn't very clear so I'm concerned that the orientation might be incorrect when the placement is imported. 

Would it be possible to please include a note or picture somewhere in the guide to show the correct orientation of U2 on the top and bottom boards?

**Comment by auipga** [comment]
I had this too, though not in the preview but confirmation via email. I used 'confirm parts placement' option (as recommended) and they showed their skills by automatically sending me pictures of corrected placements. They won't beginn the production if you don't confirm that so my guess is you won't lose your money by just trying.
The final product works as intended. (hillside52)

**Comment by jfhector** [comment]
Hello!

I've now placed and received my PCB Assembly order from JLCPCB.

I can confirm that there was no issue at all.

Specifically, in spite of the fact that the components were mis-positioned (a rotation issue) on the preview at the time of ordering:
- I received an email a few hours after ordering to ask me to check the corrected positioning. On that new visualisation the positioning was correct. If it hadn't been, I would have been able to ask for changes.
- The PCB I've received has the parts positioned in the correct way.

So, I'm closing this issue.

Also, I want to say that I'm very grateful for and impressed by both the design of Hillside, but also the thoughtful comprehensive documentation. Both were reasons why I've chosen to build Hillside 46 as my first keyboard, and I'm very excited about it. It's very close to the perfect keyboard for me. Thanks!
