### ISSUE TITLE
PCB Giveaway [EU/DE]

### ISSUE THREAD

**Issue by auipga** [mmccoyd/hillside#26]
Hi community,

The hillside52 keeb is **by far** the best keyboard I have ever used. In my opinion it really deserves more attention.

That's why I decided to gift 8 of my left over PCBs to 4 kind people who want to build their own but dread the ordering process.
All you need to pay for is shipping. Therefore it is the cheapest if you live in Germany. (~5 €)

You can contact me via Telegram. My usernames at GitHub and Telegram are the same.

Regards
Manuel

Received PCBs:
1. @johannes-jp 
2. @tokazio

**Comment by auipga** [comment]
still available:

![20230910_173437](https://github.com/mmccoyd/hillside/assets/876689/9b0afae6-341c-45a6-a5a7-7775bee2cb5d)

**Comment by tokazio** [comment]
I'm interested

**Comment by tokazio** [comment]
I've contacted you on telegram

**Comment by johannes-jp** [comment]
Mine have arrived! Thank you very much @auipga. It would have been smart for me to get tracking, but they found their way to Finland nonetheless :D

![Untitled](https://github.com/mmccoyd/hillside/assets/65911975/793d8740-810e-4654-b3f7-47f4975aba12)

**Comment by auipga** [comment]
strange... if @tokazio is your name here and for telegram then you got a message.

**Comment by tokazio** [comment]
Yes it's good

**Comment by tokazio** [comment]
Received today, awesome
![IMG_20230930_122340.jpg](https://github.com/mmccoyd/hillside/assets/7676865/5858f959-0f27-4762-b279-8130351a1e08)

Big thanks @auipga

**Comment by julientaq** [comment]
hey there.

do you still have pcb? i want to test it to try an alternative to my ferris?

**Comment by auipga** [comment]
The give away is over. All PCBs have found a new home. I'm happy to see what you are creating. I'd also be interested in your keymaps.

If you have questions or need help building I'll do my best to assist.

**Comment by julientaq** [comment]
thanks a lot @auipga!

we’ll put pictures here ⌨️

**Comment by tokazio** [comment]
![IMG_20230930_123314.jpg](https://github.com/mmccoyd/hillside/assets/7676865/c7e879f6-be08-4860-9f2b-60ae38781cb0)

![IMG_20230930_123310.jpg](https://github.com/mmccoyd/hillside/assets/7676865/33021b6d-72c1-49fb-9447-b9ac93dea886)
